import localFont from "next/font/local";
import "./globals.css";

import Providers from "../components/QueryProvider";
import Footer from "../components/Footer";
import Nav from "../components/Nav";
import Hero from "../components/hero";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="container mx-auto max-w-[1320px]">
          <div className="my-5">
            <Nav /> 
          </div>
          <Hero />
          <Providers>
            {children}
          </Providers>
        </div>
        <Footer />
      </body>
    </html>
  );
}
